### PR TITLE
Update examples to fractal-server 1.3 and fractal-tasks-core 0.10

### PR DESCRIPTION
**Pull request by tcompa**

### CODE REVIEW

**Comment by tcompa** [comment]
- [ ] In [01_cardio_tiny_dataset_with_import_export](https://github.com/fractal-analytics-platform/fractal-demos/pull/55/commits/2ea25e161a0da02aafe59ca949f3efdbc94b153a), I should go back to args file written from the script, instead of committing the json args file, unless I can find a better solution.

**Comment by tcompa** [comment]
I can't remember what is the expected output of example 03 (the multiplexing one). I've updated it, but I'm not sure that the result is fine.

This is e.g. the output of `napari --plugin napari-ome-zarr tmp_multiplex-3/20200812-CardiomyocyteDifferentiation14-Cycle1_mip.zarr/B/03/`:

Screenshot from 2023-06-16 14-12-36

@jluethi does it match with what we would expect? I think this was just due to napari not supporting multiplex, right?

**Comment by jluethi** [comment]
There should be 3 images in the B/03/ folder
1 with 1 channel. 1 with 2 channels, 1 with 3.
If you open them individually as `path/to/B/03/0`, `path/to/B/03/1` and `path/to/B/03/2`, you'll see them.
This looks correct for the first.

Also, another reason why we eventually should have some minimal form of https://github.com/fractal-analytics-platform/fractal-demos/issues/37 :)

**Comment by tcompa** [comment]
Perfect, thanks. I confirm the behavior is the expected one.

**Comment by jluethi** [comment]
Also, let's merge this branch after the example 3 again. Just ran into the failing example 01 (because of the workflow yaml paths) and it's useful to have example 01 working in main for easy testing of new setups :)

**Pull request merged**
